module.exports = {
    USER_CONNECTED :'USER_CONNECTED',
    VERIFY_USER  : 'VERIFY_USER',
    MESSAGE_RECIEVED:'MESSAGE_RECIEVED',
    MESSAGE_SENT : 'MESSAGE_SENT',
    USER_DISCONNECTED : 'USER_DISCONNECTED',
    COMMUNITY_CHAT : 'COMMUNITY_CHAT',
    TYPING : 'TYPING',
    LOGOUT: 'LOGOUT',
    PRIVATE_MESSAGE: 'PRIVATE_MESSAGE'
}