module.exports = {
    USER_CONNECTED :'USER_CONNECTED',
    VERIFY_USER  : 'VERIFY_USER',
    MESSAGE_RECIEVED:'MESSAGE_RECIEVED',
    MESSAGE_SENT : 'MESSAGE_SENT',
    USER_DISCONNECTED : 'USER_DISCONNECTED',
    TYPING : 'TYPING',
    LOGOUT: 'LOGOUT'
}